jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        # usuario administrador que puede hacer cualquier cosa
        - id: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          name: ${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}
          password: ${JENKINS_PASSWORD_ADMINISTRADOR:-AdministradorTFG2024}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_NOMBRE_ADMINISTRADOR:-administrador}"
        - 'Overall/Read:authenticated'

unclassified:
  location:
    url: http://servidor-jenkins:8080

jobs:
  # pipeline que se ejecuta correctamente
  - script: >
      pipelineJob('9-pipeline-proyecto-powershell-correcto') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  github('tfg2asircanaveral2024/9-proyecto-powershell')
                }
                branches('*/correcto')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  # pipeline que se ejecuta con errores
  - script: >
      pipelineJob('9-pipeline-proyecto-powershell-incorrecto') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  github('tfg2asircanaveral2024/9-proyecto-powershell')
                }
                branches('*/incorrecto')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }